services:
    sonata.block.exception.filter.debug_only:
        class: Sonata\BlockBundle\Exception\Filter\DebugOnlyFilter
        arguments: ["%kernel.debug%"]
        public: true
    sonata.block .exception.renderer.throw:
        class: Sonata\BlockBundle\Exception\Renderer\MonkeyThrowRenderer
        public: true

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin,group: Catalog, manager_type: orm, label: Category List }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin,group: Catalog, manager_type: orm, label: Product List }
        public: true